/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok4.ui.admin;

/**
 *
 * @author WIN 11
 */
public class admin_dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(admin_dashboard.class.getName());

    /**
     * Creates new form admin_dashboard
     */
    public admin_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelSidebar = new javax.swing.JPanel();
        jLabelNamaUser = new javax.swing.JLabel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonManageUser = new javax.swing.JButton();
        jButtonManageRole = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelKartuBarang = new javax.swing.JPanel();
        jLabelKeteranganBarang = new javax.swing.JLabel();
        jLabelTotalUser = new javax.swing.JLabel();
        jPanelKartuAlert = new javax.swing.JPanel();
        jLabelKeteranganAlert = new javax.swing.JLabel();
        jLabelTotalStaff = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jLabelDaftarBarang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanelSidebar.setBackground(new java.awt.Color(30, 58, 95));
        jPanelSidebar.setPreferredSize(new java.awt.Dimension(180, 700));

        jLabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamaUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNamaUser.setText("Admin");

        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);

        jButtonManageUser.setText("Manage User");
        jButtonManageUser.addActionListener(this::jButtonManageUserActionPerformed);

        jButtonManageRole.setText("Manage Role");
        jButtonManageRole.addActionListener(this::jButtonManageRoleActionPerformed);

        jButtonLogout.setBackground(new java.awt.Color(180, 50, 50));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);

        javax.swing.GroupLayout jPanelSidebarLayout = new javax.swing.GroupLayout(jPanelSidebar);
        jPanelSidebar.setLayout(jPanelSidebarLayout);
        jPanelSidebarLayout.setHorizontalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamaUser, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonDashboard, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonManageUser, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonManageRole, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, 0, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSidebarLayout.setVerticalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelNamaUser)
                .addGap(30, 30, 30)
                .addComponent(jButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManageUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManageRole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addContainerGap())
        );

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelTitle.setText("Dashboard Admin");

        jPanelKartuBarang.setBackground(new java.awt.Color(52, 152, 219));
        jPanelKartuBarang.setPreferredSize(new java.awt.Dimension(250, 90));

        jLabelKeteranganBarang.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKeteranganBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKeteranganBarang.setText("Total User");

        jLabelTotalUser.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelTotalUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalUser.setText("0");

        javax.swing.GroupLayout jPanelKartuBarangLayout = new javax.swing.GroupLayout(jPanelKartuBarang);
        jPanelKartuBarang.setLayout(jPanelKartuBarangLayout);
        jPanelKartuBarangLayout.setHorizontalGroup(
            jPanelKartuBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKartuBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKartuBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKeteranganBarang, 0, 238, Short.MAX_VALUE)
                    .addComponent(jLabelTotalUser, 0, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelKartuBarangLayout.setVerticalGroup(
            jPanelKartuBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKartuBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeteranganBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalUser)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanelKartuAlert.setBackground(new java.awt.Color(231, 76, 60));
        jPanelKartuAlert.setPreferredSize(new java.awt.Dimension(250, 90));

        jLabelKeteranganAlert.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKeteranganAlert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKeteranganAlert.setText("Total Staff");

        jLabelTotalStaff.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabelTotalStaff.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalStaff.setText("0");

        javax.swing.GroupLayout jPanelKartuAlertLayout = new javax.swing.GroupLayout(jPanelKartuAlert);
        jPanelKartuAlert.setLayout(jPanelKartuAlertLayout);
        jPanelKartuAlertLayout.setHorizontalGroup(
            jPanelKartuAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKartuAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKartuAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKeteranganAlert, 0, 238, Short.MAX_VALUE)
                    .addComponent(jLabelTotalStaff, 0, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelKartuAlertLayout.setVerticalGroup(
            jPanelKartuAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKartuAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeteranganAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalStaff)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama User", "NIK", "Email", "Password", "Alamat", "Phone Number", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBarang);

        jLabelDaftarBarang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelDaftarBarang.setText("Data User");

        jButton1.setText("Search");

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, 0, 870, Short.MAX_VALUE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitle)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jPanelKartuBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelKartuAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelDaftarBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelKartuBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKartuAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDaftarBarang)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, 0, 267, Short.MAX_VALUE)
                .addGap(256, 256, 256))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelMain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelSidebar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        loadData();
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageUserActionPerformed
        new form_stok_masuk(userId).setVisible(true);
    }//GEN-LAST:event_jButtonManageUserActionPerformed

    private void jButtonManageRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageRoleActionPerformed
        new form_stok_keluar(userId).setVisible(true);
    }//GEN-LAST:event_jButtonManageRoleActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
            new com.kelompok4.ui.login().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new admin_dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonManageRole;
    private javax.swing.JButton jButtonManageUser;
    private javax.swing.JLabel jLabelDaftarBarang;
    private javax.swing.JLabel jLabelKeteranganAlert;
    private javax.swing.JLabel jLabelKeteranganBarang;
    private javax.swing.JLabel jLabelNamaUser;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotalStaff;
    private javax.swing.JLabel jLabelTotalUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelKartuAlert;
    private javax.swing.JPanel jPanelKartuBarang;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
