/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok4.ui.admin;

/**
 *
 * @author WIN 11
 */
public class manage_users extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manage_users.class.getName());

    /**
     * Creates new form manage_users
     */
    public manage_users() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSupplierId2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanelSidebar = new javax.swing.JPanel();
        jLabelNamaUser = new javax.swing.JLabel();
        jButtonDashboard = new javax.swing.JButton();
        jButtonManageUser = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelForm1 = new javax.swing.JPanel();
        jLabelNoTransaksi1 = new javax.swing.JLabel();
        jTextFieldNoTransaksi1 = new javax.swing.JTextField();
        jLabelBarang1 = new javax.swing.JLabel();
        jLabelSupplierId1 = new javax.swing.JLabel();
        jTextFieldSupplierId1 = new javax.swing.JTextField();
        jLabelJumlah1 = new javax.swing.JLabel();
        jTextFieldJumlah1 = new javax.swing.JTextField();
        jLabelHarga1 = new javax.swing.JLabel();
        jTextFieldHarga1 = new javax.swing.JTextField();
        jLabelCatatan1 = new javax.swing.JLabel();
        jTextFieldCatatan1 = new javax.swing.JTextField();
        jLabelCatatan2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldSupplierId3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelDaftarBarang = new javax.swing.JLabel();

        jTextFieldSupplierId2.addActionListener(this::jTextFieldSupplierId2ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanelSidebar.setBackground(new java.awt.Color(30, 58, 95));
        jPanelSidebar.setPreferredSize(new java.awt.Dimension(180, 700));

        jLabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNamaUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNamaUser.setText("Manager");

        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);

        jButtonManageUser.setText("Manage User");
        jButtonManageUser.addActionListener(this::jButtonManageUserActionPerformed);

        jButtonLogout.setBackground(new java.awt.Color(180, 50, 50));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);

        javax.swing.GroupLayout jPanelSidebarLayout = new javax.swing.GroupLayout(jPanelSidebar);
        jPanelSidebar.setLayout(jPanelSidebarLayout);
        jPanelSidebarLayout.setHorizontalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNamaUser, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonDashboard, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonManageUser, 0, 168, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, 0, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSidebarLayout.setVerticalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelNamaUser)
                .addGap(30, 30, 30)
                .addComponent(jButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManageUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogout)
                .addContainerGap())
        );

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabelTitle.setText("Kelola User");

        jPanelForm1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input User"));

        jLabelNoTransaksi1.setText("Nama User");

        jTextFieldNoTransaksi1.setEditable(false);
        jTextFieldNoTransaksi1.addActionListener(this::jTextFieldNoTransaksi1ActionPerformed);

        jLabelBarang1.setText("NIK :");

        jLabelSupplierId1.setText("Email :");

        jTextFieldSupplierId1.addActionListener(this::jTextFieldSupplierId1ActionPerformed);

        jLabelJumlah1.setText("Password :");

        jLabelHarga1.setText("Alamat : ");

        jLabelCatatan1.setText("Phone Number :");

        jLabelCatatan2.setText("Role :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Staff Gudang", "Manager" }));

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(this::jButtonClearActionPerformed);

        jButtonAdd.setText("Add");

        jButtonEdit.setText("Edit");

        jButtonDelete.setText("Delete");

        jTextFieldSupplierId3.addActionListener(this::jTextFieldSupplierId3ActionPerformed);

        javax.swing.GroupLayout jPanelForm1Layout = new javax.swing.GroupLayout(jPanelForm1);
        jPanelForm1.setLayout(jPanelForm1Layout);
        jPanelForm1Layout.setHorizontalGroup(
            jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNoTransaksi1)
                    .addComponent(jLabelBarang1)
                    .addComponent(jLabelSupplierId1)
                    .addComponent(jLabelJumlah1)
                    .addComponent(jLabelHarga1)
                    .addComponent(jLabelCatatan1)
                    .addComponent(jLabelCatatan2))
                .addGap(18, 18, 18)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNoTransaksi1, 0, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldSupplierId1, 0, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldJumlah1, 0, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldHarga1, 0, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldCatatan1, 0, 743, Short.MAX_VALUE)
                    .addComponent(jTextFieldSupplierId3)
                    .addGroup(jPanelForm1Layout.createSequentialGroup()
                        .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelForm1Layout.createSequentialGroup()
                                .addComponent(jButtonClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelForm1Layout.setVerticalGroup(
            jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForm1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoTransaksi1)
                    .addComponent(jTextFieldNoTransaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBarang1)
                    .addComponent(jTextFieldSupplierId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupplierId1)
                    .addComponent(jTextFieldSupplierId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJumlah1)
                    .addComponent(jTextFieldJumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHarga1)
                    .addComponent(jTextFieldHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCatatan1)
                    .addComponent(jTextFieldCatatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCatatan2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelForm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete))
                .addGap(14, 14, 14))
        );

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama User", "NIK", "Email", "Password", "Alamat", "Phone Number", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableBarang);

        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jScrollPane2.setViewportView(jTextPane1);

        jLabelDaftarBarang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabelDaftarBarang.setText("Data User");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(0, 754, Short.MAX_VALUE))
                    .addComponent(jPanelForm1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, 0, 870, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelDaftarBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addGap(29, 29, 29)
                .addComponent(jPanelForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabelDaftarBarang)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, 0, 270, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanelForm1.getAccessibleContext().setAccessibleName("Input Data User");
        jPanelForm1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelMain, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelSidebar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        loadData();
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManageUserActionPerformed
        new form_stok_masuk(userId).setVisible(true);
    }//GEN-LAST:event_jButtonManageUserActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
            new com.kelompok4.ui.login().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jTextFieldSupplierId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierId1ActionPerformed

    private void jTextFieldNoTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoTransaksi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoTransaksi1ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSupplierId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierId2ActionPerformed

    private void jTextFieldSupplierId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierId3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new manage_users().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonManageUser;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox jComboBoxBarang;
    private javax.swing.JLabel jLabelBarang;
    private javax.swing.JLabel jLabelBarang1;
    private javax.swing.JLabel jLabelCatatan;
    private javax.swing.JLabel jLabelCatatan1;
    private javax.swing.JLabel jLabelCatatan2;
    private javax.swing.JLabel jLabelDaftarBarang;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JLabel jLabelHarga1;
    private javax.swing.JLabel jLabelJumlah;
    private javax.swing.JLabel jLabelJumlah1;
    private javax.swing.JLabel jLabelNamaUser;
    private javax.swing.JLabel jLabelNoTransaksi;
    private javax.swing.JLabel jLabelNoTransaksi1;
    private javax.swing.JLabel jLabelSupplierId;
    private javax.swing.JLabel jLabelSupplierId1;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelForm1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTextField jTextFieldCatatan;
    private javax.swing.JTextField jTextFieldCatatan1;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldHarga1;
    private javax.swing.JTextField jTextFieldJumlah;
    private javax.swing.JTextField jTextFieldJumlah1;
    private javax.swing.JTextField jTextFieldNoTransaksi;
    private javax.swing.JTextField jTextFieldNoTransaksi1;
    private javax.swing.JTextField jTextFieldSupplierId;
    private javax.swing.JTextField jTextFieldSupplierId1;
    private javax.swing.JTextField jTextFieldSupplierId2;
    private javax.swing.JTextField jTextFieldSupplierId3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
